insert into Labels (label_id, name, address) values (1, 'Gottlieb LLC', '371 Lerdahl Pass');
insert into Labels (label_id, name, address) values (2, 'Schroeder, Kuhlman and Ratke', '90 Burrows Crossing');
insert into Labels (label_id, name, address) values (3, 'Pagac-Hoeger', '69 Shasta Street');
insert into Labels (label_id, name, address) values (4, 'Von-Schroeder', '514 Marcy Parkway');
insert into Labels (label_id, name, address) values (5, 'Rempel-Kreiger', '9 Annamark Circle');
insert into Labels (label_id, name, address) values (6, 'Rosenbaum, Beahan and Simonis', '4024 Grim Park');
insert into Labels (label_id, name, address) values (7, 'Gleason, Towne and Witting', '0 Carpenter Alley');
insert into Labels (label_id, name, address) values (8, 'Hirthe, Lynch and Purdy', '93 Fairfield Center');
insert into Labels (label_id, name, address) values (9, 'Ledner LLC', '8 Scofield Junction');
insert into Labels (label_id, name, address) values (10, 'Langworth and Sons', '76757 Gina Hill');
insert into Labels (label_id, name, address) values (11, 'Corkery Inc', '37736 Vahlen Trail');
insert into Labels (label_id, name, address) values (12, 'Hand and Sons', '439 Rowland Circle');
insert into Labels (label_id, name, address) values (13, 'Kub-Rath', '72809 Dayton Trail');
insert into Labels (label_id, name, address) values (14, 'Cronin Group', '3 Crest Line Place');
insert into Labels (label_id, name, address) values (15, 'Bosco and Sons', '77 Nelson Way');
insert into Labels (label_id, name, address) values (16, 'Daugherty, Funk and Kautzer', '178 Hagan Drive');
insert into Labels (label_id, name, address) values (17, 'Marvin LLC', '805 Derek Park');
insert into Labels (label_id, name, address) values (18, 'Lebsack Group', '041 Menomonie Street');
insert into Labels (label_id, name, address) values (19, 'Bosco-Denesik', '29 South Crossing');
insert into Labels (label_id, name, address) values (20, 'Waelchi LLC', '71504 Pine View Parkway');
insert into Labels (label_id, name, address) values (21, 'Cronin LLC', '81 Thompson Road');
insert into Labels (label_id, name, address) values (22, 'Wilderman and Sons', '900 Mifflin Circle');
insert into Labels (label_id, name, address) values (23, 'Walter-Jacobson', '8 Manley Circle');
insert into Labels (label_id, name, address) values (24, 'Stanton-Kilback', '1 West Hill');
insert into Labels (label_id, name, address) values (25, 'Powlowski LLC', '57606 Merrick Plaza');
insert into Labels (label_id, name, address) values (26, 'Wilderman Inc', '632 Transport Pass');
insert into Labels (label_id, name, address) values (27, 'Metz Group', '03909 Merry Way');
insert into Labels (label_id, name, address) values (28, 'Reynolds-Gusikowski', '486 Hanover Junction');
insert into Labels (label_id, name, address) values (29, 'Kihn and Sons', '6 Ramsey Crossing');
insert into Labels (label_id, name, address) values (30, 'Satterfield and Sons', '04414 Park Meadow Way');
