insert into Services (service_id, creative_id, title, price) values (1, 1, 'Real Men', 341.53);
insert into Services (service_id, creative_id, title, price) values (2, 2, 'Frozen', 13.37);
insert into Services (service_id, creative_id, title, price) values (3, 3, 'Treasure Hunter, The (Ci ling)', 794.03);
insert into Services (service_id, creative_id, title, price) values (4, 4, 'Greatest Story Ever Told, The', 683.15);
insert into Services (service_id, creative_id, title, price) values (5, 5, 'Goliyon Ki Raasleela Ram-Leela', 434.29);
insert into Services (service_id, creative_id, title, price) values (6, 6, 'Soap and Water', 762.5);
insert into Services (service_id, creative_id, title, price) values (7, 7, 'Waiting Game, The', 716.84);
insert into Services (service_id, creative_id, title, price) values (8, 8, 'Romanzo Criminale', 331.42);
insert into Services (service_id, creative_id, title, price) values (9, 9, 'Love Me Tender', 814.34);
insert into Services (service_id, creative_id, title, price) values (10, 10, 'Skin Too Few: The Days of Nick Drake, A', 522.67);
insert into Services (service_id, creative_id, title, price) values (11, 11, 'Hateship Loveship', 126.51);
insert into Services (service_id, creative_id, title, price) values (12, 12, 'Brave, The', 179.39);
insert into Services (service_id, creative_id, title, price) values (13, 13, 'Big Bang Love, Juvenile A (46-okunen no koi)', 359.39);
insert into Services (service_id, creative_id, title, price) values (14, 14, 'Evidence ', 28.08);
insert into Services (service_id, creative_id, title, price) values (15, 15, 'Danton', 508.19);
insert into Services (service_id, creative_id, title, price) values (16, 16, 'Earthlings', 969.25);
insert into Services (service_id, creative_id, title, price) values (17, 17, 'High Plains Drifter', 907.4);
insert into Services (service_id, creative_id, title, price) values (18, 18, 'Twice-Told Tales', 148.38);
insert into Services (service_id, creative_id, title, price) values (19, 19, 'Gasland Part II', 130.48);
insert into Services (service_id, creative_id, title, price) values (20, 20, 'Kung Pow: Enter the Fist', 951.04);
insert into Services (service_id, creative_id, title, price) values (21, 21, 'Country Bears, The', 235.86);
insert into Services (service_id, creative_id, title, price) values (22, 22, 'Sherlock Holmes Faces Death', 902.54);
insert into Services (service_id, creative_id, title, price) values (23, 23, 'Wartorn: 1861-2010', 993.57);
insert into Services (service_id, creative_id, title, price) values (24, 24, 'Pornorama', 330.88);
insert into Services (service_id, creative_id, title, price) values (25, 25, 'Tigger Movie, The', 991.11);
insert into Services (service_id, creative_id, title, price) values (26, 26, 'Two for the Money', 433.39);
insert into Services (service_id, creative_id, title, price) values (27, 27, 'Happy Accidents', 885.46);
insert into Services (service_id, creative_id, title, price) values (28, 28, 'Hans Christian Andersen', 371.19);
insert into Services (service_id, creative_id, title, price) values (29, 29, 'Left Behind: The Movie', 402.11);
insert into Services (service_id, creative_id, title, price) values (30, 30, 'AM1200', 36.14);
insert into Services (service_id, creative_id, title, price) values (31, 31, 'Un vampiro para dos', 79.02);
insert into Services (service_id, creative_id, title, price) values (32, 32, 'Tribes', 59.29);
insert into Services (service_id, creative_id, title, price) values (33, 33, 'Anna Nicole (Anna Nicole Smith Story, The)', 353.65);
insert into Services (service_id, creative_id, title, price) values (34, 34, 'Long Day Closes, The', 946.96);
insert into Services (service_id, creative_id, title, price) values (35, 35, 'Sleep Tight (Mientras duermes)', 428.6);
insert into Services (service_id, creative_id, title, price) values (36, 36, 'Ali Baba Goes to Town', 193.26);
insert into Services (service_id, creative_id, title, price) values (37, 37, 'Scream', 676.83);
insert into Services (service_id, creative_id, title, price) values (38, 38, 'Gold', 831.25);
insert into Services (service_id, creative_id, title, price) values (39, 39, 'God Bless America', 973.15);
insert into Services (service_id, creative_id, title, price) values (40, 40, 'I Know Where I''m Going!', 13.42);
insert into Services (service_id, creative_id, title, price) values (41, 41, 'Man of Marble (Czlowiek z Marmuru)', 840.61);
insert into Services (service_id, creative_id, title, price) values (42, 42, 'Next Door (Naboer)', 452.12);
insert into Services (service_id, creative_id, title, price) values (43, 43, 'According to Greta', 212.1);
insert into Services (service_id, creative_id, title, price) values (44, 44, 'Defense of the Realm', 178.03);
insert into Services (service_id, creative_id, title, price) values (45, 45, 'Still Life', 135.49);
insert into Services (service_id, creative_id, title, price) values (46, 46, 'Saw V', 921.07);
insert into Services (service_id, creative_id, title, price) values (47, 47, 'Footlight Parade', 106.59);
insert into Services (service_id, creative_id, title, price) values (48, 48, 'Home and the World, The (Ghare-Baire)', 393.19);
insert into Services (service_id, creative_id, title, price) values (49, 49, 'High Cost of Living, The', 849.4);
insert into Services (service_id, creative_id, title, price) values (50, 50, 'Aces: Iron Eagle III', 807.56);
insert into Services (service_id, creative_id, title, price) values (51, 51, 'Collateral', 920.09);
insert into Services (service_id, creative_id, title, price) values (52, 52, 'Courage Mountain', 931.12);
insert into Services (service_id, creative_id, title, price) values (53, 53, 'Thumbelina', 894.41);
insert into Services (service_id, creative_id, title, price) values (54, 54, 'Gozu (Gokudô kyôfu dai-gekijô: Gozu)', 954.89);
insert into Services (service_id, creative_id, title, price) values (55, 55, 'Phantom Carriage, The (Körkarlen)', 16.4);
insert into Services (service_id, creative_id, title, price) values (56, 56, 'Blue Collar', 400.41);
insert into Services (service_id, creative_id, title, price) values (57, 57, 'Joe the King', 258.36);
insert into Services (service_id, creative_id, title, price) values (58, 58, 'Final Destination 5', 962.93);
insert into Services (service_id, creative_id, title, price) values (59, 59, 'Church, The (Chiesa, La)', 28.91);
insert into Services (service_id, creative_id, title, price) values (60, 60, 'The Mystery of the Leaping Fish', 230.54);
insert into Services (service_id, creative_id, title, price) values (61, 61, 'Electric Dragon 80.000 V', 754.4);
insert into Services (service_id, creative_id, title, price) values (62, 62, 'Miss Zombie', 790.32);
insert into Services (service_id, creative_id, title, price) values (63, 63, 'Lodger, The', 495.89);
insert into Services (service_id, creative_id, title, price) values (64, 64, 'Peter Ibbetson', 556.64);
insert into Services (service_id, creative_id, title, price) values (65, 65, 'Wild Horse, Wild Ride', 490.66);
insert into Services (service_id, creative_id, title, price) values (66, 66, 'Into the Abyss', 951.93);
insert into Services (service_id, creative_id, title, price) values (67, 67, 'Transporter, The', 555.04);
insert into Services (service_id, creative_id, title, price) values (68, 68, 'Christmas Carol, A', 358.32);
insert into Services (service_id, creative_id, title, price) values (69, 69, 'Class of 1999 II: The Substitute', 637.51);
insert into Services (service_id, creative_id, title, price) values (70, 70, 'Finding a Family', 602.29);
